name: Call API Workflow

on:
  push:
    branches:
      - main

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
    - name: Make API Request
      run: |
        curl -X GET "https://api.example.com/endpoint" \
          -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" \
          -H "Content-Type: application/json"
